# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/CompareIndicatorsLite.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(386, 566)
        self.headerLabel = QtWidgets.QLabel(Form)
        self.headerLabel.setGeometry(QtCore.QRect(16, 10, 351, 21))
        self.headerLabel.setObjectName("headerLabel")
        self.firstIndicatorLabel = QtWidgets.QLabel(Form)
        self.firstIndicatorLabel.setGeometry(QtCore.QRect(10, 40, 361, 20))
        self.firstIndicatorLabel.setObjectName("firstIndicatorLabel")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 64, 361, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.firstIndListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.firstIndListWidget.setGeometry(QtCore.QRect(0, 0, 361, 211))
        self.firstIndListWidget.setObjectName("firstIndListWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.secondIndicatorLabel = QtWidgets.QLabel(Form)
        self.secondIndicatorLabel.setGeometry(QtCore.QRect(9, 283, 361, 20))
        self.secondIndicatorLabel.setObjectName("secondIndicatorLabel")
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 307, 361, 221))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 359, 219))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.secondIndListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.secondIndListWidget.setGeometry(QtCore.QRect(0, 0, 361, 221))
        self.secondIndListWidget.setObjectName("secondIndListWidget")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(290, 536, 81, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.headerLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\">Упрощенное сравнение показателей</p></body></html>"))
        self.firstIndicatorLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\">Первый показатель</p></body></html>"))
        self.secondIndicatorLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\">Второй показатель</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
